import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  ArrowRight, 
  Globe2, 
  Building2, 
  ShoppingCart, 
  Zap, 
  Shield, 
  TrendingDown,
  CheckCircle,
  Play,
  ChevronDown,
  FolderOpen,
  FileText
} from "lucide-react";
import { Button } from "../components/ui/button";

// ============================================
// BRAND ASSETS
// ============================================
const OMNISUPPLY_LOGO = "https://customer-assets.emergentagent.com/job_3d3497d4-96ce-45f6-9a33-f8d277c4c70e/artifacts/tt4qnc6b_OMNISupply.png";
const INFOSYS_BPM_LOGO = "https://customer-assets.emergentagent.com/job_3d3497d4-96ce-45f6-9a33-f8d277c4c70e/artifacts/i0gp8i5o_InfosysBPM.png";

// Supplier logos generated by AI
const SUPPLIERS = [
  { name: "Grainger", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/c0aa7f54b52fc1914890e0ceb1572e94023339c8c575e16b6ee7073438392034.png", color: "#C8102E" },
  { name: "MOTION", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/4a9dfce8cdd9e6412455e1c2d31c280f3f724beaeff7a2b230b1371065257c84.png", color: "#003087" },
  { name: "BDI", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/faea8b3b0bcc38e39236a401776e00c48ed255f6c2e5b5a43fc0a33511a19741.png", color: "#1E3A8A" },
  { name: "Fastenal", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/f64c0515eecabe7b5d65a0e53879267a164f4ff20b51f4fb7d8b622d4bffa21d.png", color: "#00843D" },
  { name: "Donaldson", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/a502c8d4141a49107460a5b68f254b3a9d0aa70023baec16b4d12ef9e079c9ac.png", color: "#0033A0" },
  { name: "Avantor", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/bf516738c5b7b5de2e7e9edcd62bef5955371cb32775f24c48ccd7cb945deec9.png", color: "#6B2D5B" },
  { name: "MARKEM", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/356f6e7784c5a7d104a0f6eb7b8f5d5cf56b5f3ad3c86aea7cb39a08e330a9bb.png", color: "#FF6600" },
  { name: "VideoJet", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/0f18ee277ae1b48f9a2e59999772ed1ff99c9b740aea4f93a1844ce433fd2dee.png", color: "#00529B" },
  { name: "Sonepar", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/025bc34befa2a4da52b73571af0f19d06c7ad82fcdd30e2da7c2de4f9b0ce889.png", color: "#E4002B" },
  { name: "Cromwell", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/692d901d97d7a222edf20f26848c2bcb7eb4cffc43d561fc8516bdf80414e83c.png", color: "#ED1C24" },
  { name: "NorthSky", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/25a7d0a65e1882dba3e8337b1f4e9001e81c900926aa746126214147f2cd4263.png", color: "#C41E3A" },
  { name: "ProPay", logo: "https://static.prod-images.emergentagent.com/jobs/3d3497d4-96ce-45f6-9a33-f8d277c4c70e/images/b32ad9763bf7545918655c0f1f258098b006edbd83e23fd0a2a55e1646420035.png", color: "#4A90D9" },
];

// ============================================
// SUPPLIER FILE CARD - Like a document/file
// ============================================
const SupplierFileCard = ({ supplier, index, phase, onDropComplete }) => {
  // Positions for the scattered layout (left side)
  const startPositions = [
    { x: -420, y: -180 }, { x: -380, y: -60 }, { x: -440, y: 60 }, { x: -400, y: 180 },
    { x: -320, y: -140 }, { x: -340, y: 40 }, { x: -360, y: 160 }, { x: -280, y: -60 },
    { x: -300, y: 80 }, { x: -260, y: -160 }, { x: -240, y: 20 }, { x: -220, y: 140 },
  ];
  
  const startPos = startPositions[index % startPositions.length];
  
  // Calculate drop animation delay
  const dropDelay = index * 0.15;
  
  return (
    <motion.div
      initial={{ 
        x: startPos.x, 
        y: startPos.y, 
        opacity: 0, 
        scale: 0.8,
        rotate: -5 + Math.random() * 10 
      }}
      animate={
        phase === "scattered" 
          ? { 
              x: startPos.x, 
              y: startPos.y, 
              opacity: 1, 
              scale: 1,
              rotate: -5 + Math.random() * 10,
              transition: { delay: index * 0.08, duration: 0.5, ease: "backOut" }
            }
          : phase === "dropping"
          ? {
              x: 0,
              y: 80,
              opacity: 0,
              scale: 0.3,
              rotate: 0,
              transition: { 
                delay: dropDelay, 
                duration: 0.6, 
                ease: [0.45, 0, 0.55, 1],
                opacity: { delay: dropDelay + 0.4, duration: 0.2 }
              }
            }
          : { 
              x: startPos.x, 
              y: startPos.y, 
              opacity: 0, 
              scale: 0.5 
            }
      }
      onAnimationComplete={() => {
        if (phase === "dropping" && index === SUPPLIERS.length - 1) {
          setTimeout(onDropComplete, 300);
        }
      }}
      className="absolute"
      style={{ zIndex: SUPPLIERS.length - index }}
    >
      {/* File/Document Card */}
      <div className="relative w-28 h-36 md:w-32 md:h-40">
        {/* File shape with folded corner */}
        <div className="absolute inset-0 bg-white rounded-lg shadow-xl overflow-hidden border border-slate-200">
          {/* Folded corner effect */}
          <div className="absolute top-0 right-0 w-6 h-6">
            <div className="absolute top-0 right-0 w-0 h-0 border-l-[24px] border-l-transparent border-t-[24px] border-t-slate-100" />
            <div className="absolute top-0 right-0 w-0 h-0 border-l-[20px] border-l-transparent border-b-[20px] border-b-white" style={{ transform: 'rotate(-90deg) translateX(-20px)' }} />
          </div>
          
          {/* Content */}
          <div className="p-3 h-full flex flex-col">
            {/* Logo */}
            <div className="flex-1 flex items-center justify-center bg-slate-50 rounded mb-2">
              <img 
                src={supplier.logo} 
                alt={supplier.name}
                className="max-w-full max-h-16 object-contain p-1"
                onError={(e) => {
                  e.target.style.display = 'none';
                }}
              />
            </div>
            
            {/* Vendor name */}
            <div 
              className="text-center py-1.5 rounded text-white text-xs font-bold"
              style={{ backgroundColor: supplier.color }}
            >
              {supplier.name}
            </div>
          </div>
        </div>
        
        {/* Cart icon badge */}
        <div className="absolute -top-2 -right-2 w-7 h-7 bg-[#007ABF] rounded-full flex items-center justify-center shadow-lg border-2 border-white">
          <ShoppingCart className="w-3.5 h-3.5 text-white" />
        </div>
      </div>
    </motion.div>
  );
};

// ============================================
// INFOSHOP FOLDER - The destination
// ============================================
const InfoShopFolder = ({ isReceiving, itemsReceived }) => {
  return (
    <motion.div 
      className="relative"
      animate={isReceiving ? { scale: [1, 1.05, 1] } : { scale: 1 }}
      transition={{ duration: 0.3, repeat: isReceiving ? Infinity : 0, repeatDelay: 0.5 }}
    >
      {/* Glow effect when receiving */}
      {isReceiving && (
        <motion.div
          className="absolute inset-0 rounded-2xl"
          style={{
            background: 'radial-gradient(circle, rgba(0,122,191,0.4) 0%, transparent 70%)',
            filter: 'blur(20px)',
          }}
          animate={{ scale: [1, 1.3, 1], opacity: [0.5, 0.8, 0.5] }}
          transition={{ duration: 1, repeat: Infinity }}
        />
      )}
      
      {/* Folder Base */}
      <div className="relative w-64 h-48 md:w-80 md:h-56">
        {/* Folder back */}
        <div className="absolute inset-0 bg-gradient-to-br from-[#007ABF] to-[#005A8C] rounded-2xl shadow-2xl">
          {/* Folder tab */}
          <div className="absolute -top-4 left-6 w-24 h-6 bg-gradient-to-r from-[#007ABF] to-[#0090D9] rounded-t-lg" />
        </div>
        
        {/* Folder front (open) */}
        <motion.div 
          className="absolute inset-x-0 bottom-0 h-[85%] bg-gradient-to-br from-[#0090D9] to-[#007ABF] rounded-b-2xl rounded-t-lg shadow-inner"
          animate={isReceiving ? { rotateX: -10 } : { rotateX: 0 }}
          style={{ transformOrigin: 'bottom', perspective: 1000 }}
        >
          {/* Folder content area */}
          <div className="absolute inset-4 bg-white/10 rounded-xl flex flex-col items-center justify-center backdrop-blur-sm">
            {/* OMNISupply Logo */}
            <img 
              src={OMNISUPPLY_LOGO} 
              alt="OMNISupply.io" 
              className="h-10 md:h-12 mb-2"
            />
            
            {/* InfoShop text - sleek styling */}
            <div className="flex items-center gap-2 mb-1">
              <div className="w-8 h-0.5 bg-white/40 rounded" />
              <span className="text-white/90 text-sm font-light tracking-[0.2em] uppercase">
                InfoShop
              </span>
              <div className="w-8 h-0.5 bg-white/40 rounded" />
            </div>
            
            <span className="text-white/60 text-xs tracking-wider">
              Digital Catalog
            </span>
            
            {/* Items counter */}
            {itemsReceived > 0 && (
              <motion.div
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                className="mt-3 bg-white text-[#007ABF] px-4 py-1.5 rounded-full text-sm font-bold shadow-lg"
              >
                {itemsReceived} Suppliers Consolidated
              </motion.div>
            )}
          </div>
        </motion.div>
        
        {/* Folder icon */}
        <FolderOpen className="absolute -top-2 right-4 w-8 h-8 text-white/80" />
      </div>
    </motion.div>
  );
};

// ============================================
// STATS CARD
// ============================================
const StatCard = ({ icon: Icon, value, label, delay }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    whileInView={{ opacity: 1, y: 0 }}
    transition={{ delay, duration: 0.5 }}
    viewport={{ once: true }}
    className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20 hover:bg-white/15 transition-colors"
  >
    <Icon className="w-8 h-8 text-[#E97300] mb-3" />
    <div className="text-3xl font-bold text-white mb-1">{value}</div>
    <div className="text-white/70 text-sm">{label}</div>
  </motion.div>
);

// ============================================
// MAIN LANDING PAGE
// ============================================
const InfoShopLandingPage = ({ onEnterCatalog }) => {
  const [animationPhase, setAnimationPhase] = useState("idle"); // idle, scattered, dropping, complete
  const [itemsReceived, setItemsReceived] = useState(0);
  const animationRef = useRef(null);

  const startAnimation = () => {
    setAnimationPhase("scattered");
    setItemsReceived(0);
    
    // After cards appear, start dropping
    setTimeout(() => {
      setAnimationPhase("dropping");
      
      // Increment counter as items drop
      SUPPLIERS.forEach((_, i) => {
        setTimeout(() => {
          setItemsReceived(prev => prev + 1);
        }, i * 150 + 400);
      });
    }, 1500);
  };

  const handleDropComplete = () => {
    setAnimationPhase("complete");
  };

  const resetAnimation = () => {
    setAnimationPhase("idle");
    setItemsReceived(0);
    setTimeout(startAnimation, 300);
  };

  const scrollToAnimation = () => {
    animationRef.current?.scrollIntoView({ behavior: 'smooth' });
    setTimeout(startAnimation, 600);
  };

  return (
    <div className="min-h-screen bg-[#0D1B2A] overflow-x-hidden">
      {/* ============================================ */}
      {/* HERO SECTION */}
      {/* ============================================ */}
      <section className="relative min-h-screen flex flex-col">
        {/* Background */}
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-br from-[#0D1B2A] via-[#1B2838] to-[#0D1B2A]" />
          <motion.div
            animate={{ backgroundPosition: ["0% 0%", "100% 100%"] }}
            transition={{ duration: 25, repeat: Infinity, repeatType: "reverse" }}
            className="absolute inset-0 opacity-30"
            style={{
              backgroundImage: `radial-gradient(ellipse at 30% 30%, #007ABF 0%, transparent 50%), 
                               radial-gradient(ellipse at 70% 70%, #00A9E0 0%, transparent 50%)`,
            }}
          />
          {/* Grid */}
          <div className="absolute inset-0 opacity-[0.03]" style={{
            backgroundImage: `linear-gradient(rgba(255,255,255,1) 1px, transparent 1px), 
                             linear-gradient(90deg, rgba(255,255,255,1) 1px, transparent 1px)`,
            backgroundSize: '60px 60px'
          }} />
        </div>

        {/* Header */}
        <header className="relative z-10 px-6 py-5">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="flex items-center gap-5">
              <img src={OMNISUPPLY_LOGO} alt="OMNISupply.io" className="h-10 md:h-12" />
              <div className="hidden sm:flex items-center gap-2 border-l-2 border-white/20 pl-5">
                <div className="w-6 h-0.5 bg-[#00A9E0] rounded" />
                <span className="text-white/80 text-sm tracking-wider">InfoShop</span>
              </div>
            </div>
            
            <div className="flex items-center gap-4">
              <span className="hidden md:block text-white/40 text-xs">Powered by</span>
              <div className="bg-white rounded-lg px-3 py-1.5 shadow-md">
                <img src={INFOSYS_BPM_LOGO} alt="Infosys BPM" className="h-6 md:h-7" />
              </div>
            </div>
          </div>
        </header>

        {/* Hero Content */}
        <div className="relative z-10 flex-1 flex flex-col items-center justify-center px-6 text-center py-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-5xl"
          >
            {/* Badge */}
            <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm px-5 py-2.5 rounded-full mb-8 border border-white/20">
              <Globe2 className="w-5 h-5 text-[#00A9E0]" />
              <span className="text-white/90 text-sm font-medium">Global Digital One Stop Shop</span>
            </div>
            
            {/* Main Headline */}
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold mb-6 leading-tight">
              <span className="text-white">You Deal with </span>
              <span className="bg-gradient-to-r from-[#00A9E0] to-[#007ABF] bg-clip-text text-transparent">One</span>
              <br />
              <span className="text-white">We Deal with </span>
              <span className="text-[#E97300]">Many</span>
            </h1>

            {/* Subheadline */}
            <p className="text-lg md:text-xl text-white/60 max-w-3xl mx-auto mb-10 leading-relaxed">
              Consolidate <span className="text-[#00A9E0] font-semibold">hundreds of supplier catalogs</span> into 
              one unified platform. <span className="text-white/80">Simplify procurement. Maximize savings.</span>
            </p>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-12">
              <Button 
                onClick={scrollToAnimation}
                size="lg"
                className="bg-gradient-to-r from-[#007ABF] to-[#00A9E0] hover:from-[#006AA3] hover:to-[#0095C7] text-white font-semibold px-8 py-6 text-lg shadow-lg shadow-[#007ABF]/30 rounded-xl"
              >
                <Play className="w-5 h-5 mr-2" />
                Watch the Magic
              </Button>
              <Button 
                onClick={onEnterCatalog}
                size="lg"
                className="bg-[#E97300] hover:bg-[#D66900] text-white font-semibold px-8 py-6 text-lg rounded-xl"
              >
                Enter Catalog
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </div>

            {/* Trust Badges */}
            <div className="flex flex-wrap items-center justify-center gap-8 text-white/50 text-sm">
              <div className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-[#00A9E0]" />
                <span>Enterprise Security</span>
              </div>
              <div className="flex items-center gap-2">
                <Zap className="w-5 h-5 text-[#E97300]" />
                <span>Coupa PunchOut</span>
              </div>
              <div className="flex items-center gap-2">
                <TrendingDown className="w-5 h-5 text-green-400" />
                <span>15-25% Savings</span>
              </div>
            </div>
          </motion.div>

          {/* Scroll indicator */}
          <motion.div 
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
            className="absolute bottom-8 cursor-pointer"
            onClick={scrollToAnimation}
          >
            <ChevronDown className="w-8 h-8 text-white/30" />
          </motion.div>
        </div>
      </section>

      {/* ============================================ */}
      {/* CONSOLIDATION ANIMATION SECTION */}
      {/* ============================================ */}
      <section ref={animationRef} className="relative py-24 px-6 bg-gradient-to-b from-[#0D1B2A] to-[#152238] overflow-hidden">
        <div className="max-w-7xl mx-auto">
          {/* Section Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4">
              Multiple Webshops <span className="text-[#E97300]">→</span> One Catalog
            </h2>
            <p className="text-white/50 text-lg max-w-2xl mx-auto">
              See how supplier catalogs consolidate into InfoShop
            </p>
          </motion.div>

          {/* Animation Container */}
          <div className="relative h-[500px] md:h-[550px] flex items-center justify-center">
            {/* Supplier Files */}
            {SUPPLIERS.map((supplier, index) => (
              <SupplierFileCard
                key={supplier.name}
                supplier={supplier}
                index={index}
                phase={animationPhase}
                onDropComplete={handleDropComplete}
              />
            ))}

            {/* InfoShop Folder - Center Right */}
            <div className="relative z-20" style={{ marginLeft: '100px' }}>
              <InfoShopFolder 
                isReceiving={animationPhase === "dropping"} 
                itemsReceived={itemsReceived}
              />
            </div>

            {/* Arrow indicator */}
            {animationPhase === "scattered" && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1, x: [0, 10, 0] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-20 text-white/30"
              >
                <ArrowRight className="w-12 h-12" />
              </motion.div>
            )}

            {/* Controls */}
            <div className="absolute bottom-0 left-1/2 -translate-x-1/2 flex flex-col items-center gap-3">
              {animationPhase === "idle" && (
                <Button
                  onClick={startAnimation}
                  size="lg"
                  className="bg-[#E97300] hover:bg-[#D66900] text-white font-semibold shadow-lg rounded-xl"
                >
                  <Play className="w-5 h-5 mr-2" />
                  Start Consolidation
                </Button>
              )}
              
              {animationPhase === "complete" && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex flex-col items-center gap-3"
                >
                  <Button
                    onClick={onEnterCatalog}
                    size="lg"
                    className="bg-gradient-to-r from-[#007ABF] to-[#00A9E0] hover:from-[#006AA3] hover:to-[#0095C7] text-white font-bold px-12 py-6 text-lg shadow-xl shadow-[#007ABF]/40 rounded-xl"
                  >
                    <CheckCircle className="w-6 h-6 mr-2" />
                    Enter InfoShop Catalog
                  </Button>
                  <button 
                    onClick={resetAnimation}
                    className="text-white/40 hover:text-white/70 text-sm underline"
                  >
                    Watch again
                  </button>
                </motion.div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* ============================================ */}
      {/* STATS SECTION */}
      {/* ============================================ */}
      <section className="py-20 px-6 bg-[#152238]">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <StatCard icon={Building2} value="26+" label="Partner Suppliers" delay={0} />
            <StatCard icon={ShoppingCart} value="3M+" label="Products Available" delay={0.1} />
            <StatCard icon={Globe2} value="4" label="Global Regions" delay={0.2} />
            <StatCard icon={TrendingDown} value="15-25%" label="Average Savings" delay={0.3} />
          </div>
        </div>
      </section>

      {/* ============================================ */}
      {/* VALUE PROPS */}
      {/* ============================================ */}
      <section className="py-20 px-6 bg-gradient-to-b from-[#152238] to-[#0D1B2A]">
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { icon: Zap, title: "One Login", description: "Access millions of products from trusted suppliers worldwide." },
              { icon: TrendingDown, title: "Real Savings", description: "Infosys-negotiated discounts with transparent Danone pricing." },
              { icon: Shield, title: "Enterprise Ready", description: "Coupa PunchOut enabled. SOC2 compliant. Zero training." }
            ].map((item, index) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10 hover:border-[#007ABF]/50 transition-all hover:-translate-y-1"
              >
                <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-[#007ABF] to-[#00A9E0] flex items-center justify-center mb-6 shadow-lg">
                  <item.icon className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">{item.title}</h3>
                <p className="text-white/50 leading-relaxed">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================ */}
      {/* FINAL CTA */}
      {/* ============================================ */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="relative rounded-3xl overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-[#007ABF] to-[#00A9E0]" />
            <div className="relative px-8 py-16 md:px-16 text-center">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
                Ready to Simplify Procurement?
              </h2>
              <p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">
                Join enterprises saving 15-25% with consolidated supplier catalogs.
              </p>
              <Button
                onClick={onEnterCatalog}
                size="lg"
                className="bg-white text-[#007ABF] hover:bg-white/90 font-bold px-12 py-6 text-lg shadow-xl rounded-xl"
              >
                Start Browsing
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ============================================ */}
      {/* FOOTER */}
      {/* ============================================ */}
      <footer className="py-12 px-6 border-t border-white/10 bg-[#0D1B2A]">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <img src={OMNISUPPLY_LOGO} alt="OMNISupply.io" className="h-8" />
            <span className="text-white/30 text-sm">InfoShop Digital Catalog</span>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-white/30 text-sm">Powered by</span>
            <div className="bg-white rounded-lg px-2 py-1">
              <img src={INFOSYS_BPM_LOGO} alt="Infosys BPM" className="h-5" />
            </div>
          </div>
          <div className="text-white/30 text-sm">
            © {new Date().getFullYear()} Infosys Limited
          </div>
        </div>
      </footer>
    </div>
  );
};

export default InfoShopLandingPage;
